### ISSUE TITLE
No recipes available for: linux-ti-staging_4.9 and  u-boot-ti-staging_2017.01

### ISSUE THREAD

**Issue by messi1** [everclear72216/meta-mb#2]
Hi
thanks for the project.
Mean while they have upgraded to the new linux-ti-staging-4.14 kernel.
I will try to upgrade it.

**Comment by everclear72216** [comment]
Thanks for the heads up, supporting the new ti kernel would be great.

**Comment by messi1** [comment]
Detect another problem with qt and qtwayland.
Version mismatch: You used 5.9.2, now the version is 5.9.4

ERROR: qtwayland-native-5.9.4+gitAUTOINC+83db09bd0a-r0 do_patch: Command Error: 'quilt --quiltrc /home/jpm/BBB/build-rocko/tmp/work/x86_64-linux/qtwayland-native/5.9.4+gitAUTOINC+83db09bd0a-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-qtwayland-remove-xkbcommon-dependency.patch
patching file src/client/client.pro
patching file src/compositor/compositor.pro
patching file src/compositor/compositor_api/qwaylandkeyboard.cpp
patching file src/compositor/wayland_wrapper/wayland_wrapper.pri
patching file src/plugins/shellintegration/ivi-shell/ivi-shell.pro
patching file tests/auto/compositor/compositor/compositor.pro
Hunk #1 FAILED at 7.
1 out of 1 hunk FAILED -- rejects in file tests/auto/compositor/compositor/compositor.pro
Patch 0001-qtwayland-remove-xkbcommon-dependency.patch does not apply (enforce with -f)
ERROR: qtwayland-native-5.9.4+gitAUTOINC+83db09bd0a-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/jpm/BBB/build-rocko/tmp/work/x86_64-linux/qtwayland-native/5.9.4+gitAUTOINC+83db09bd0a-r0/temp/log.do_patch.30917
ERROR: Task (virtual:native:/home/jpm/BBB/poky-rocko/meta-qt5/recipes-qt/qt5/qtwayland_git.bb:do_patch) failed with exit code '1'

**Comment by everclear72216** [comment]
Ok I just checked the meta-qt repo and it seems that Qt changed the release their rocko-branch ist pointing to. This of course may break the patch I did for the qtwayland project files. I did not expect something like this to happen. I will have to look into this and decide whether to upgrade to 5.9.4 or change the readme so folks get the sources the patches work with.

**Comment by everclear72216** [comment]
As it seems there is no support for linux 4.14 in the ti-sgx-ddk-km kernel module as of now. I looked into it more deeply. A few things changed in the kernel's DRM support. The changes cannot simply be patched into the module. I also think that I only scrached the surface of porting the kernel module to 4.14. However without it, there will be no graphics acceleration for QML. Therefore I will stick with the second option and change the documentation.

**Comment by messi1** [comment]
Damit. Yesterday I tooked the uboot and kernel 4.9 recipies from morty-next.
The creation of the image worked after commenting out the qtwayland stuff.

One question, why did you activate the wayland when you are set the QPA environment variable to eglfs?

**Comment by everclear72216** [comment]
I just built with Qt5.9.4 which seems to be working fine using meta-ti from around Christmas 2017. It seems the Wayland stuff was fixed in the meantime, so the patch is not necessary anymore. Wayland integration was kind of my first plan on getting Qt to work with multi-window support. This was a requirement for the machinekit client software I have a meta-layer for in another repo. Since I was unable to get it to run how I wanted I resorted to changing the machinekit client to use only one window (still a work in progress). So Wayland is a relic from an experiment. I'm not sure whether there were any other dependencies to that package though.

**Comment by messi1** [comment]
Thanks for the info. Since you are using machinekit, did you activate the PRUs?

**Comment by everclear72216** [comment]
No machinekit is running on a second beaglebone that uses a standard debian distro with dtb overlays, thus the PRUs come literally for free. You will not be able to do this on a single beaglebone anyway since you need an "rt"-kernel for machinekit, which is not supported by the graphics driver.
