### ISSUE TITLE
eglinfo is not working

### ISSUE THREAD

**Issue by messi1** [everclear72216/meta-mb#5]
Hi Martin
I tried to start your image.
Unfortunately it didn't start because uboot was looking for a uenv file.
So I provided mine which I wrote years ago.
Now the image started. After booting I tried eglinfo.
Which result in the error at the end.
Any ideas why?
Thanks.

> bootpart=0:2

> bootdir=/boot
> bootfile=zImage
> console=ttyO0,115200n8

> fdt_high=0xffffffff
> fdtaddr=0x88000000
> fdtfile=am335x-boneblack.dtb

> loadaddr=0x82000000
> mmcroot=/dev/mmcblk0p2 ro
> mmcrootfstype=ext4 rootwait
> optargs=consoleblank=0 video=HDMI-A-1:1024x768@60 drm.debug=0x3f 
> mmcargs=setenv bootargs console=${console} ${optargs} root=${mmcroot} rootfstype=${mmcrootfstype}
> loadfdt=load mmc ${bootpart} ${fdtaddr} ${bootdir}/${fdtfile}
> loadimage=load mmc ${bootpart} ${loadaddr} ${bootdir}/${bootfile}
> uenvcmd=if run loadfdt; then echo Loaded ${fdtfile}; if run loadimage; then run mmcargs; bootz ${loadaddr} - ${fdtaddr}; fi; fi;

> eglinfo 
> PVR:(Error): WSEGL_InitialiseDisplay: Failed to create output [0, ]
> Unable to initialise egl
>     egl error 'EGL_NOT_INITIALIZED' (0x3001)

**Comment by everclear72216** [comment]
The issue you are seing is that the sgx kernel module was not loaded: Either because the devicetree did not enable the device or because the module is not built into the kernel. Since everything works fine on my machine I'm gonna have to do some basic trouble-shooting with you:
Are you sure you used the commit from meta-ti that i'm now specifiying in the README.md? During my tests I also flashed the rootfs and definitely removed any pre-existing uEnv.txt. uEnv.txt is optional and Since it is not generated by yocto it is not necessary. Please remove your uEnv.txt beacuase it conflicts with the way I'm handling loading of the dtb files. Make sure that in your /boot directory on the rootfs there is a symbolic link "devicetree.dtb" that points to the dtb-file for the 7" touch screen.

**Comment by messi1** [comment]
Thanks for the tip. No I ported the 4.9 stuff to the rocko release.
I'm now checking out the commit which you mentioned in the readme, clean all and start a rebuild.

**Comment by messi1** [comment]
Hi Martin
after a clean build I recreated  a new image.
Unfortunately it didn't boot.
Now the only difference could be in creating the image.
I made a script for that.
My partition looks like this:
Disk /dev/sdd: 14.7 GiB, 15811477504 bytes, 30881792 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot   Start     End Sectors   Size Id Type
/dev/sdd1  *         63  144584  144522  70.6M  c W95 FAT32 (LBA)
/dev/sdd2        160650 3132674 2972025   1.4G 83 Linux
/dev/sdd3       3148740 4192964 1044225 509.9M 83 Linux

Have you set any variables in the uboot or did you changed the GPIO55?
Any other ideas?
Thanks a lot.



>> picocom /dev/ttyUSB0 -b 115200
picocom v1.7

port is        : /dev/ttyUSB0
flowcontrol    : none
baudrate is    : 115200
parity is      : none
databits are   : 8
escape is      : C-a
local echo is  : no
noinit is      : no
noreset is     : no
nolock is      : no
send_cmd is    : sz -vv
receive_cmd is : rz -vv
imap is        : 
omap is        : 
emap is        : crcrlf,delbs,

Terminal ready
�
U-Boot SPL 2013.04-dirty (May 06 2013 - 16:12:47)
musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Peripheral mode controller at 47401000 using PIO, IRQ 0
musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Host mode controller at 47401800 using PIO, IRQ 0
OMAP SD/MMC: 0
mmc_send_cmd : timeout: No status update
reading u-boot.img
reading u-boot.img


U-Boot 2013.04-dirty (May 06 2013 - 16:12:47)

I2C:   ready
DRAM:  512 MiB
WARNING: Caches not enabled
NAND:  No NAND device found!!!
0 MiB
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
*** Warning - readenv() failed, using default environment

musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Peripheral mode controller at 47401000 using PIO, IRQ 0
musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Host mode controller at 47401800 using PIO, IRQ 0
Net:   <ethaddr> not set. Validating first E-fuse MAC
cpsw, usb_ether
Hit any key to stop autoboot:  0 
gpio: pin 53 (gpio 53) value is 1
mmc0 is current device
micro SD card found
mmc0 is current device
gpio: pin 54 (gpio 54) value is 1
SD/MMC found on device 0
reading uEnv.txt
** Unable to read file uEnv.txt **
gpio: pin 55 (gpio 55) value is 1
** File not found /boot/uImage **
U-Boot#

**Comment by everclear72216** [comment]
Comparing sizes or checksums won't do any good. The results will vary because the date and sometimes also the name of the machine building it is compiled into the artifacts.

The logs you sent indicate that you still have the wrong version of u-boot. 2013.04 instead of 2017.01.
Please try running "bitbake -c cleansstate virtual/bootloader". Also clean sstate for the rootfs. Then rebuild.

**Comment by messi1** [comment]
Hi Martin
I have fixed the issue. It was on my side.
The script created a Fat32 boot partition instead of Fat16.
And there was also an old uboot and kernel on the emmc memory.
So the new stuff didn't boot correctly. Now the eglinfo worked correctly.
Now I will try  to activate the HDMI port for some small test with QML.

One point is a little bit awkward, why have checked in two times defconfig in the recipes-kernel? 
Thanks for your effort.

**Comment by everclear72216** [comment]
I'm glad you could solve the problem. Hope it works with HDMI. I  patched the dts file for HDMI as well but never came around to testing it. Maybe you could share if it is working or not?

**Comment by messi1** [comment]
Keep you informed when I find it out.
Can you explain me why two defconfig in recipes-kernel?
